# See https://wiki.hypr.land/Configuring/Keywords/
$mainMod = SUPER # Sets "Windows" key as main modifier

plugin {
    hyprsplit {
        persistant_workspaces = 6
        new_workspaces = 4
        monitor_priority = eDP-1,DP-2
    }
}
# Example binds, see https://wiki.hypr.land/Configuring/Binds/ for more
bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod SHIFT, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, Z, exec, $menu
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, J, layoutmsg, togglesplit # dwindle
bind = $mainMod, K, layoutmsg, swapsplit # dwindle
bind = $mainMod, B, exec, $browser
bind = $mainMod, W, exec, pkill waybar && waybar &
bind = $mainMod, A, fullscreen

# Move focus with mainMod + arrow keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

bind = $mainMod SHIFT, left, exec, ~/.config/hypr/scripts/switch_mon.sh
bind = $mainMod SHIFT, right, exec, ~/.config/hypr/scripts/switch_mon.sh

bind = SUPER, 1, split:workspace, 1
bind = SUPER, 2, split:workspace, 2
bind = SUPER, 3, split:workspace, 3
bind = SUPER, 4, split:workspace, 4
bind = SUPER, 5, split:workspace, 5
bind = SUPER, 6, split:workspace, 6
bind = SUPER, 7, split:workspace, 7
bind = SUPER, 8, split:workspace, 8
bind = SUPER, 9, split:workspace, 9
bind = SUPER, 0, split:workspace, 10

bind = SUPER SHIFT, 1, split:movetoworkspacesilent, 1
bind = SUPER SHIFT, 2, split:movetoworkspacesilent, 2
bind = SUPER SHIFT, 3, split:movetoworkspacesilent, 3
bind = SUPER SHIFT, 4, split:movetoworkspacesilent, 4
bind = SUPER SHIFT, 5, split:movetoworkspacesilent, 5
bind = SUPER SHIFT, 6, split:movetoworkspacesilent, 6
bind = SUPER SHIFT, 7, split:movetoworkspacesilent, 7
bind = SUPER SHIFT, 8, split:movetoworkspacesilent, 8
bind = SUPER SHIFT, 9, split:movetoworkspacesilent, 9
bind = SUPER SHIFT, 0, split:movetoworkspacesilent, 10

bind = SUPER, D, split:swapactiveworkspaces, current +1
bind = SUPER , G, togglegroup
bind = $mainMod ALT, left, changegroupactive, b # Go to previous stacked windows
bind = $mainMod ALT, right, changegroupactive, f # Go to previous stacked windows
bind = $mainMod CONTROL, left, changegroupactive, b # Go to previous stacked windows
bind = $mainMod CONTROL, right, changegroupactive, f # Go to previous stacked windows
# Only bind if hyprsplit plugin is loaded, requires Hyprland >= v0.51.0
# hyprlang if HYPRSPLIT
bind = SUPER CONTROL, 1, split:movetoworkspace, 1
# hyprlang endif

# Example special workspace (scratchpad)
bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic


# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Laptop multimedia keys for volume and LCD brightness
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-

# Requires playerctl
bindl = , XF86AudioNext, exec, playerctl -p spotify,%any next
bindl = , XF86AudioPause, exec, playerctl -p spotify,%any play-pause
bindl = , XF86AudioPlay, exec, playerctl -p spotify,%any play-pause
bindl = , XF86AudioPrev, exec, playerctl -p spotify,%any previous

# Example binds, see https://wiki.hypr.land/Configuring/Binds/ for more
# Screenshot a window
bind = $mainMod , X, exec, hyprshot -m window
bind = $mainMod SHIFT, X, exec, hyprshot -m region

bind = SUPER,L,exec,hyprlock

