#Key Bindings
unbind C-B
set -g prefix `

set -g default-terminal "tmux-256color"

bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

bind-key "|" split-window -h -c "#{pane_current_path}"
bind-key "\\" split-window -fh -c "#{pane_current_path}"
bind-key "-" split-window -v -c "#{pane_current_path}"
bind-key "_" split-window -fv -c "#{pane_current_path}"

bind f resize-pane -Z
bind-key h set-option status

#Options
set -g mouse on

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

set -g status-position top
set -g status-justify absolute-centre
set -g status-style "bg=default"
set -g window-status-current-style "fg=color0"
set -g status-left ""
set -g status-right ""

set -g window-status-format " #I "
set -g window-status-current-format " #I "
set -g window-status-bell-style "bg=color9,nobold"
set -g window-status-current-style "bg=#{?window_zoomed_flag,color3,white},nobold"

set-option -g status-position top
set -g pane-border-lines simple

set -g escape-time 0
set -g repeat-time 500
