#############################
### ENVIRONMENT VARIABLES ###
#############################

source = ~/.config/hypr/core/env.conf

################
### MONITORS ###
################

source = ~/.config/hypr/core/monitors.conf

#################
### AUTOSTART ###
#################

source = ~/.config/hypr/core/auto-start.conf

###################
### MY PROGRAMS ###
###################

source = ~/.config/hypr/core/programs.conf

###################
### PERMISSIONS ###
###################

source = ~/.config/hypr/core/permission.conf

#####################
### LOOK AND FEEL ###
#####################

# Refer to https://wiki.hypr.land/Configuring/Variables/
source = ~/.cache/wal/colors-hyprland.conf
source = ~/.config/hypr/core/dwindle.conf
source = ~/.config/hypr/core/general.conf
source = ~/.config/hypr/core/decoration.conf
source = ~/.config/hypr/core/animations.conf
source = ~/.config/hypr/core/windowrule.conf
# source = ~/.config/hypr/core/master.conf
source = ~/.config/hypr/core/misc.conf

#############
### INPUT ###
#############

source = ~/.config/hypr/core/input.conf
source = ~/.config/hypr/core/gestures.conf
source = ~/.config/hypr/core/device.conf
source = ~/.config/hypr/core/groups.conf

###################
### KEYBINDINGS ###
###################

source = ~/.config/hypr/core/keybind.conf

##############################
### WINDOWS AND WORKSPACES ###
##############################

source = ~/.config/hypr/core/workspace-rule.conf


permission = /usr/(bin|local/bin)/hyprpm, plugin, allow
